version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories:
      - '/'
      - /api/'
      - '/front/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    cooldown:
      default-days: 7
      exclude:
        - 'pnpm'
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        versions: ["25.*"]
