packages:
  - ./api
  - ./front

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

legacyPeerDeps: true

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
  ws: '>=8.17.1'

strictPeerDependencies: false
