packages:
  - './api'
  - './front'

engineStrict: true

### https://thedaviddias.dev/notes/how-to-fix-post-pre-build-pnpm
enablePrePostScripts: true

strictPeerDependencies: false

legacyPeerDeps: true
autoInstallPeers: true

overrides: 
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  ws: ">=8.17.1"